name: Update awesome list

on:
  push:
  pull_request:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/simonecorsi/mawesome
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-name: ${{ secrets.USER_NAME }}
          github-email: ${{ secrets.USER_EMAIL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
